# Generated by Django 3.1.5 on 2021-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Текстовое поле')),
                ('num', models.IntegerField(blank=True, verbose_name='Числовое поле')),
                ('bol', models.BooleanField(default=True, verbose_name='Логическое поле')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
                'ordering': ['id'],
            },
        ),
    ]
