# Generated by Django 3.1.5 on 2021-02-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210207_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uniCat',
            field=models.SlugField(blank=True, max_length=35, unique=True, verbose_name='Urls'),
        ),
    ]
